import React, { useState } from 'react';
import { API_URL } from '../../config/api';
import { useAuth } from '@clerk/clerk-react';
import { 
  Database, Download, FileText, Code, CheckCircle, AlertCircle, X, RefreshCw 
} from 'lucide-react';

interface Props {
  consultationId: string;
  onClose: () => void;
}

export default function EMRExportModal({ consultationId, onClose }: Props) {
  const { getToken } = useAuth();
  const [downloadingFormat, setDownloadingFormat] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  const handleDownload = async (format: string, fileExtension: string) => {
    setDownloadingFormat(format);
    setSuccessMessage(null);
    try {
      const token = await getToken();
      const response = await fetch(`${API_URL}/emr/export/${consultationId}?format=${format}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });

      if (!response.ok) {
        throw new Error(`Server returned status ${response.status}`);
      }

      let blob: Blob;
      if (format === 'pdf') {
        blob = await response.blob();
      } else if (format === 'hl7') {
        const text = await response.text();
        blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
      } else {
        const json = await response.json();
        blob = new Blob([JSON.stringify(json, null, 2)], { type: 'application/json;charset=utf-8' });
      }

      // Trigger standard browser download
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `emr_${format}_${consultationId}.${fileExtension}`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      setSuccessMessage(`Successfully downloaded ${format.toUpperCase()} EMR report!`);
      setTimeout(() => setSuccessMessage(null), 4000);
    } catch (error: any) {
      console.error('EMR download failed:', error);
      alert('Failed to download report: ' + error.message);
    } finally {
      setDownloadingFormat(null);
    }
  };

  return (
    <div style={styles.overlay}>
      <div style={styles.modal}>
        <div style={styles.header}>
          <div style={styles.titleGroup}>
            <Database size={22} color="#3b82f6" />
            <h2 style={styles.title}>EMR Compatible Export</h2>
          </div>
          <button onClick={onClose} style={styles.closeBtn}>
            <X size={18} />
          </button>
        </div>

        <div style={styles.content}>
          <p style={styles.subtitle}>Select the standard interoperability format to download the voice consultation record for clinical integration.</p>

          {successMessage && (
            <div style={styles.successAlert}>
              <CheckCircle size={18} />
              <span>{successMessage}</span>
            </div>
          )}

          <div style={styles.exportList}>
            {/* Format 1: SOAP Clinical Summary PDF */}
            <div style={styles.exportCard}>
              <div style={styles.cardInfo}>
                <div style={styles.cardHeader}>
                  <FileText size={20} color="#3b82f6" />
                  <h4>SOAP Progress Summary (PDF)</h4>
                </div>
                <p>Printable clinical document outlining Subjective, Objective, Assessment, and Plan notes generated by the AI agent.</p>
              </div>
              <button 
                onClick={() => handleDownload('pdf', 'pdf')}
                disabled={downloadingFormat !== null}
                style={styles.downloadBtn}
              >
                {downloadingFormat === 'pdf' ? <RefreshCw style={styles.spinner} size={14} /> : <Download size={14} />}
                <span>Download PDF</span>
              </button>
            </div>

            {/* Format 2: FHIR R4 Bundle */}
            <div style={styles.exportCard}>
              <div style={styles.cardInfo}>
                <div style={styles.cardHeader}>
                  <Code size={20} color="#10b981" />
                  <h4>HL7 FHIR R4 Transaction Bundle (JSON)</h4>
                </div>
                <p>Standard HL7 FHIR Bundle mapping the consultation into linked Encounter, Observation, Condition, and DocumentReference resources.</p>
              </div>
              <button 
                onClick={() => handleDownload('fhir-bundle', 'json')}
                disabled={downloadingFormat !== null}
                style={{...styles.downloadBtn, backgroundColor: '#10b981'}}
              >
                {downloadingFormat === 'fhir-bundle' ? <RefreshCw style={styles.spinner} size={14} /> : <Download size={14} />}
                <span>Download FHIR Bundle</span>
              </button>
            </div>

            {/* Format 3: HL7 V2 Message */}
            <div style={styles.exportCard}>
              <div style={styles.cardInfo}>
                <div style={styles.cardHeader}>
                  <FileText size={20} color="#f59e0b" />
                  <h4>HL7 V2 ORU^R01 Message (Text)</h4>
                </div>
                <p>Traditional pipe-delimited segment message structure (MSH, PID, PV1, OBR, OBX) used in legacy hospital information networks.</p>
              </div>
              <button 
                onClick={() => handleDownload('hl7', 'txt')}
                disabled={downloadingFormat !== null}
                style={{...styles.downloadBtn, backgroundColor: '#f59e0b'}}
              >
                {downloadingFormat === 'hl7' ? <RefreshCw style={styles.spinner} size={14} /> : <Download size={14} />}
                <span>Download HL7</span>
              </button>
            </div>

            {/* Format 4: Structured JSON Report */}
            <div style={styles.exportCard}>
              <div style={styles.cardInfo}>
                <div style={styles.cardHeader}>
                  <Code size={20} color="#8b5cf6" />
                  <h4>Structured Medical JSON</h4>
                </div>
                <p>A complete data package containing detailed demographics, voice transcripts, emotion scoring, and assessment notes for analytics.</p>
              </div>
              <button 
                onClick={() => handleDownload('structured', 'json')}
                disabled={downloadingFormat !== null}
                style={{...styles.downloadBtn, backgroundColor: '#8b5cf6'}}
              >
                {downloadingFormat === 'structured' ? <RefreshCw style={styles.spinner} size={14} /> : <Download size={14} />}
                <span>Download JSON</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

const styles = {
  overlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(15, 23, 42, 0.55)',
    backdropFilter: 'blur(6px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1100,
  },
  modal: {
    background: 'var(--bg-card)',
    borderRadius: '16px',
    maxWidth: '650px',
    width: '90%',
    boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)',
    overflow: 'hidden',
    border: '1px solid var(--border-color)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottom: '1px solid var(--border-color)',
  },
  titleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  title: {
    margin: 0,
    fontSize: '18px',
    fontWeight: '700',
    color: 'var(--text-primary)',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    padding: '4px',
  },
  content: {
    padding: '20px',
  },
  subtitle: {
    margin: '0 0 20px 0',
    fontSize: '14px',
    color: 'var(--text-secondary)',
    lineHeight: '1.5',
  },
  successAlert: {
    backgroundColor: 'var(--status-completed-bg)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    padding: '10px 14px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: 'var(--status-completed-text)',
    fontSize: '13px',
    marginBottom: '16px',
  },
  exportList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  exportCard: {
    border: '1px solid var(--border-color)',
    borderRadius: '10px',
    padding: '14px 18px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    backgroundColor: 'var(--bg-primary)',
    color: 'var(--text-primary)',
  },
  cardInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    h4: {
      margin: 0,
      fontSize: '14px',
      fontWeight: '600',
      color: 'var(--text-primary)',
    }
  },
  downloadBtn: {
    backgroundColor: '#3b82f6',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    padding: '8px 14px',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    whiteSpace: 'nowrap' as const,
  },
  spinner: {
    animation: 'spin 1s linear infinite',
  }
};
