import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface ReportData {
  id: string;
  consultationId: string;
  patientName: string;
  specialistType: string;
  specialistName: string;
  date: Date;
  symptoms: string;
  diagnosis: string;
  recommendations: string[];
  medications: string[];
  followUpNeeded: boolean;
  followUpDate?: Date;
  duration: number;
  notes: string;
}

export const generatePDFReport = async (reportData: ReportData): Promise<void> => {
  const element = document.createElement('div');
  element.innerHTML = `
    <div style="padding: 40px; font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
      <!-- Header -->
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #667eea; padding-bottom: 20px;">
        <h1 style="color: #667eea; margin: 0;">🏥 AI Medical Voice Agent</h1>
        <h2 style="color: #333; margin: 10px 0 0;">Medical Consultation Report</h2>
        <p style="color: #666; margin: 5px 0 0;">AI-Powered Healthcare Consultation</p>
      </div>

      <!-- Report ID and Date -->
      <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
        <table style="width: 100%;">
          <tr>
            <td style="padding: 5px;"><strong>Report ID:</strong></td>
            <td style="padding: 5px;">${reportData.id}</td>
            <td style="padding: 5px;"><strong>Consultation ID:</strong></td>
            <td style="padding: 5px;">${reportData.consultationId}</td>
          </tr>
          <tr>
            <td style="padding: 5px;"><strong>Date:</strong></td>
            <td style="padding: 5px;">${new Date(reportData.date).toLocaleDateString()}</td>
            <td style="padding: 5px;"><strong>Time:</strong></td>
            <td style="padding: 5px;">${new Date(reportData.date).toLocaleTimeString()}</td>
          </tr>
          <tr>
            <td style="padding: 5px;"><strong>Duration:</strong></td>
            <td style="padding: 5px;">${reportData.duration} minutes</td>
            <td style="padding: 5px;"><strong>Specialist:</strong></td>
            <td style="padding: 5px;">${reportData.specialistName} (${reportData.specialistType})</td>
          </tr>
        </table>
      </div>

      <!-- Patient Information -->
      <div style="margin-bottom: 20px;">
        <h3 style="color: #667eea; border-left: 4px solid #667eea; padding-left: 10px;">Patient Information</h3>
        <p><strong>Name:</strong> ${reportData.patientName}</p>
      </div>

      <!-- Symptoms -->
      <div style="margin-bottom: 20px;">
        <h3 style="color: #667eea; border-left: 4px solid #667eea; padding-left: 10px;">Symptoms</h3>
        <p style="background: #f8f9fa; padding: 15px; border-radius: 8px;">${reportData.symptoms}</p>
      </div>

      <!-- Diagnosis -->
      <div style="margin-bottom: 20px;">
        <h3 style="color: #667eea; border-left: 4px solid #667eea; padding-left: 10px;">Diagnosis & Assessment</h3>
        <p style="background: #f8f9fa; padding: 15px; border-radius: 8px;">${reportData.diagnosis}</p>
      </div>

      <!-- Recommendations -->
      <div style="margin-bottom: 20px;">
        <h3 style="color: #667eea; border-left: 4px solid #667eea; padding-left: 10px;">Recommendations</h3>
        <ul style="background: #f8f9fa; padding: 15px 15px 15px 35px; border-radius: 8px;">
          ${reportData.recommendations.map(rec => `<li style="margin-bottom: 8px;">${rec}</li>`).join('')}
        </ul>
      </div>

      <!-- Medications -->
      <div style="margin-bottom: 20px;">
        <h3 style="color: #667eea; border-left: 4px solid #667eea; padding-left: 10px;">Medications</h3>
        <ul style="background: #f8f9fa; padding: 15px 15px 15px 35px; border-radius: 8px;">
          ${reportData.medications.map(med => `<li style="margin-bottom: 8px;">${med}</li>`).join('')}
        </ul>
      </div>

      <!-- Follow-up -->
      <div style="margin-bottom: 20px;">
        <h3 style="color: #667eea; border-left: 4px solid #667eea; padding-left: 10px;">Follow-up Plan</h3>
        <div style="background: #f8f9fa; padding: 15px; border-radius: 8px;">
          <p><strong>Follow-up Needed:</strong> ${reportData.followUpNeeded ? 'Yes' : 'No'}</p>
          ${reportData.followUpDate ? `<p><strong>Suggested Date:</strong> ${new Date(reportData.followUpDate).toLocaleDateString()}</p>` : ''}
          <p><strong>Notes:</strong> ${reportData.notes}</p>
        </div>
      </div>

      <!-- Footer -->
      <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px;">
        <p>This is an AI-generated medical report. Please consult with a qualified healthcare provider for medical advice.</p>
        <p>Generated by AI Medical Voice Agent | ${new Date().toLocaleString()}</p>
      </div>
    </div>
  `;

  document.body.appendChild(element);
  
  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      backgroundColor: '#ffffff',
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });
    
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;
    
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
    
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }
    
    pdf.save(`Medical_Report_${reportData.id}.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Error generating PDF. Please try again.');
  } finally {
    document.body.removeChild(element);
  }
};

export const generateMockReportData = (consultationId: string, specialistType: string, symptoms: string): ReportData => {
  const recommendationsMap: Record<string, string[]> = {
    general: [
      'Get plenty of rest (7-8 hours of sleep)',
      'Stay hydrated with warm fluids',
      'Take over-the-counter medication for fever if needed',
      'Monitor temperature every 4-6 hours',
      'Eat light, nutritious meals',
      'Avoid strenuous activities',
    ],
    orthopedic: [
      'Apply ice pack to affected area for 15-20 minutes',
      'Rest and avoid strenuous activities',
      'Gentle stretching exercises',
      'Use proper posture when sitting/standing',
      'Consider physical therapy if pain persists',
    ],
    cardiologist: [
      'Monitor blood pressure regularly',
      'Reduce salt and caffeine intake',
      'Light walking for 20 minutes daily',
      'Practice stress management techniques',
      'Avoid heavy meals before bedtime',
    ],
    neurologist: [
      'Get adequate sleep (7-8 hours)',
      'Reduce screen time',
      'Stay hydrated throughout the day',
      'Practice relaxation techniques',
      'Keep a headache diary',
    ],
    pediatrician: [
      'Ensure child gets plenty of rest',
      'Keep hydrated with fluids',
      'Monitor temperature every 4 hours',
      'Provide nutritious, easy-to-digest diet',
      'Keep child comfortable',
    ],
  };

  const medicationsMap: Record<string, string[]> = {
    general: [
      'Acetaminophen for fever (as needed)',
      'Ibuprofen for pain (if no contraindications)',
      'Multivitamins for immune support',
    ],
    orthopedic: [
      'Over-the-counter anti-inflammatory medication',
      'Topical pain relief cream',
      'Calcium and Vitamin D supplements',
    ],
    cardiologist: [
      'As prescribed by your cardiologist',
      'Blood pressure medication (if prescribed)',
      'Cholesterol medication (if needed)',
    ],
    neurologist: [
      'As prescribed by your neurologist',
      'Magnesium supplements (if recommended)',
      'Vitamin B complex',
    ],
    pediatrician: [
      'Age-appropriate fever reducer',
      'Pediatric electrolyte solution',
      'Children\'s multivitamins',
    ],
  };

  return {
    id: `REPORT_${Date.now()}`,
    consultationId: consultationId,
    patientName: 'Patient Name', // You can get this from auth
    specialistType: specialistType,
    specialistName: `${specialistType.charAt(0).toUpperCase() + specialistType.slice(1)} Specialist`,
    date: new Date(),
    symptoms: symptoms,
    diagnosis: `Based on the consultation, the patient presented with: ${symptoms}. The AI doctor has assessed the condition and provided recommendations accordingly.`,
    recommendations: recommendationsMap[specialistType] || recommendationsMap.general,
    medications: medicationsMap[specialistType] || medicationsMap.general,
    followUpNeeded: true,
    followUpDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days later
    duration: Math.floor(Math.random() * 20) + 10,
    notes: 'Patient advised to monitor symptoms and follow recommendations. Schedule follow-up if symptoms persist or worsen.',
  };
};